// <auto-generated />
using Manager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manager.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Manager.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "SCS Company",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Microsoft Company",
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Tichnical Company",
                            Name = "TICH"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Enginerrnig Company",
                            Name = "ENGINNER"
                        },
                        new
                        {
                            Id = 5,
                            Location = " SCS Company",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Google Company",
                            Name = "CEO"
                        });
                });

            modelBuilder.Entity("Manager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            Department = 1,
                            Email = "Ali@gmail.com",
                            ImagePath = "",
                            Name = "Ali",
                            PhoneNumber = "0777777777"
                        },
                        new
                        {
                            Id = 2,
                            Age = 33,
                            Department = 5,
                            Email = "Khaled@gmail.com",
                            ImagePath = "",
                            Name = "khaled",
                            PhoneNumber = "0792999999"
                        },
                        new
                        {
                            Id = 3,
                            Age = 56,
                            Department = 2,
                            Email = "Sam@gmail.com",
                            ImagePath = "",
                            Name = "Sam",
                            PhoneNumber = "0792346332"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
